"use strict";(()=>{var e={};e.id=703,e.ids=[703],e.modules={1698:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},5863:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>h,requestAsyncStorage:()=>m,routeModule:()=>p,serverHooks:()=>d,staticGenerationAsyncStorage:()=>f});var a={};r.r(a),r.d(a,{GET:()=>c});var o=r(9303),n=r(8716),l=r(670),i=r(5661),s=r(9150),u=r(707);async function c(){let e=await {rules:{userAgent:"*",allow:"/"},sitemap:`${s.J.url}/sitemap.xml`},t=(0,u.resolveRouteData)(e,"robots");return new i.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let p=new o.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2Fhome%2Fcarlosz%2Flandingpage_clarium%2Fsrc%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:a}),{requestAsyncStorage:m,staticGenerationAsyncStorage:f,serverHooks:d}=p,g="/robots.txt/route";function h(){return(0,l.patchFetch)({serverHooks:d,staticGenerationAsyncStorage:f})}},707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return l},resolveRobots:function(){return o},resolveRouteData:function(){return i},resolveSitemap:function(){return n}});let a=r(1389);function o(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,a.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,a.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,a.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,a.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function n(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let o of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var a;r+=`<url>
<loc>${o.url}</loc>
`;let e=null==(a=o.alternates)?void 0:a.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(o.lastModified){let e=o.lastModified instanceof Date?o.lastModified.toISOString():o.lastModified;r+=`<lastmod>${e}</lastmod>
`}o.changeFrequency&&(r+=`<changefreq>${o.changeFrequency}</changefreq>
`),"number"==typeof o.priority&&(r+=`<priority>${o.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function l(e){return JSON.stringify(e)}function i(e,t){return"robots"===t?o(e):"sitemap"===t?n(e):"manifest"===t?l(e):""}},1389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function a(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return a}})},9150:(e,t,r)=>{r.d(t,{J:()=>a});let a={name:"Clarium",tagline:"Organize suas finan\xe7as com clareza.",description:"Clarium \xe9 um app de gerenciamento financeiro minimalista, gratuito, offline e totalmente local. Organiza\xe7\xe3o financeira simples, clara e segura para qualquer pessoa.",url:process.env.NEXT_PUBLIC_SITE_URL??"https://clarium.app",apkUrl:process.env.NEXT_PUBLIC_APK_URL??"",repos:{site:process.env.NEXT_PUBLIC_SITE_REPO_URL??"",app:process.env.NEXT_PUBLIC_APP_REPO_URL??"https://github.com/CarlossgLuz/controle-fatura",appBranch:process.env.NEXT_PUBLIC_APP_REPO_BRANCH??"feat/home-shell",siteLicense:"MIT"},locales:["pt-BR","en","es"],defaultLocale:"pt-BR",author:{name:"Carlos Gabriel",linkedin:"https://www.linkedin.com/in/dev-carlosgabriel/",github:"https://github.com/CarlossgLuz/",email:"carlosgabriel.contato2007@gmail.com",pix:"carlosgabriel.contato2007@gmail.com"},links:{linkedin:"https://www.linkedin.com/in/dev-carlosgabriel/",github:"https://github.com/CarlossgLuz/",email:"mailto:carlosgabriel.contato2007@gmail.com"}}}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[948,518],()=>r(5863));module.exports=a})();