"use strict";(()=>{var e={};e.id=717,e.ids=[717],e.modules={1698:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8240:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>w,patchFetch:()=>x,requestAsyncStorage:()=>v,routeModule:()=>h,serverHooks:()=>_,staticGenerationAsyncStorage:()=>y});var a={};r.r(a),r.d(a,{default:()=>c});var n={};r.r(n),r.d(n,{GET:()=>g});var l=r(9303),o=r(8716),i=r(670),s=r(5661),u=r(9150);function c(){return u.J.locales.map(e=>({url:`${u.J.url}/${e}`,lastModified:new Date,changeFrequency:"monthly",priority:e===u.J.defaultLocale?1:.8,alternates:{languages:Object.fromEntries(u.J.locales.map(e=>[e,`${u.J.url}/${e}`]))}}))}var p=r(707);let m={...a},f=m.default,d=m.generateSitemaps;if("function"!=typeof f)throw Error('Default export is missing in "/home/carlosz/landingpage_clarium/src/app/sitemap.ts"');async function g(e,t){let r;let{__metadata_id__:a,...n}=t.params||{},l=d?await d():null;if(l&&null==(r=l.find(e=>{let t=e.id.toString();return(t+=".xml")===a})?.id))return new s.NextResponse("Not Found",{status:404});let o=await f({id:r}),i=(0,p.resolveRouteData)(o,"sitemap");return new s.NextResponse(i,{headers:{"Content-Type":"application/xml","Cache-Control":"public, max-age=0, must-revalidate"}})}let h=new l.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/sitemap.xml/route",pathname:"/sitemap.xml",filename:"sitemap",bundlePath:"app/sitemap.xml/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Fsitemap.xml%2Froute&filePath=%2Fhome%2Fcarlosz%2Flandingpage_clarium%2Fsrc%2Fapp%2Fsitemap.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:n}),{requestAsyncStorage:v,staticGenerationAsyncStorage:y,serverHooks:_}=h,w="/sitemap.xml/route";function x(){return(0,i.patchFetch)({serverHooks:_,staticGenerationAsyncStorage:y})}},707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return o},resolveRobots:function(){return n},resolveRouteData:function(){return i},resolveSitemap:function(){return l}});let a=r(1389);function n(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,a.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,a.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,a.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,a.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function l(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let n of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var a;r+=`<url>
<loc>${n.url}</loc>
`;let e=null==(a=n.alternates)?void 0:a.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(n.lastModified){let e=n.lastModified instanceof Date?n.lastModified.toISOString():n.lastModified;r+=`<lastmod>${e}</lastmod>
`}n.changeFrequency&&(r+=`<changefreq>${n.changeFrequency}</changefreq>
`),"number"==typeof n.priority&&(r+=`<priority>${n.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function o(e){return JSON.stringify(e)}function i(e,t){return"robots"===t?n(e):"sitemap"===t?l(e):"manifest"===t?o(e):""}},1389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function a(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return a}})},9150:(e,t,r)=>{r.d(t,{J:()=>a});let a={name:"Clarium",tagline:"Organize suas finan\xe7as com clareza.",description:"Clarium \xe9 um app de gerenciamento financeiro minimalista, gratuito, offline e totalmente local. Organiza\xe7\xe3o financeira simples, clara e segura para qualquer pessoa.",url:process.env.NEXT_PUBLIC_SITE_URL??"https://clarium.app",apkUrl:process.env.NEXT_PUBLIC_APK_URL??"",repos:{site:process.env.NEXT_PUBLIC_SITE_REPO_URL??"",app:process.env.NEXT_PUBLIC_APP_REPO_URL??"https://github.com/CarlossgLuz/controle-fatura",appBranch:process.env.NEXT_PUBLIC_APP_REPO_BRANCH??"feat/home-shell",siteLicense:"MIT"},locales:["pt-BR","en","es"],defaultLocale:"pt-BR",author:{name:"Carlos Gabriel",linkedin:"https://www.linkedin.com/in/dev-carlosgabriel/",github:"https://github.com/CarlossgLuz/",email:"carlosgabriel.contato2007@gmail.com",pix:"carlosgabriel.contato2007@gmail.com"},links:{linkedin:"https://www.linkedin.com/in/dev-carlosgabriel/",github:"https://github.com/CarlossgLuz/",email:"mailto:carlosgabriel.contato2007@gmail.com"}}}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[948,518],()=>r(8240));module.exports=a})();